### ISSUE TITLE
Permission denied downloading ATAC matrices

### ISSUE THREAD

**Issue by adamgayoso** [shendurelab/mouse-atac#4]
Hello,

It appears there is some block on downloading data from the website.

**Comment by hypercompetent** [comment]
Hi Adam,

I've needed to use command-line tools for some of the files in the past. Have you tried wget or curl?

**Comment by GrossTor** [comment]
Hello,
I encountered the same problem trying to download the ATAC mouse bigwig files. Independently of whether I use the web interface or command line tools, I get e.g.

> You don't have permission to access /content/members/ajh24/mouse_atlas_data_release/bigwigs/Activated_B_cells-clusters_4-cluster_4.bw

Can someone provide the permission? Thanks.

Torsten

**Comment by cusanovich** [comment]
This should be resolved now. Let me know if you're still having issues with this. Apologies!
